'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

import { createContext } from "react";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export const FooterContext = createContext(
  {} as {
    FooterIndex: number;
    setFooterIndex: React.Dispatch<React.SetStateAction<number>>;
  },
);


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [FooterIndex,setFooterIndex]=useState<number>(0);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 w-auto`}
      >
        
        <FooterContext.Provider value={{ FooterIndex, setFooterIndex }}>
        {children}
        </FooterContext.Provider>
        <FooterContext.Provider value={{ FooterIndex, setFooterIndex }}>
        <Footer />
        </FooterContext.Provider>
        
        
      </body>
    </html>
  );
}
